---
- name: Filling in the inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add build host
      add_host:
        hostname: "{{ vm_ip }}"
        groups: jenkins

- name: Installing Jenkins
  hosts: jenkins
  become: yes
  vars:
    - keyring: /usr/share/keyrings/jenkins-keyring.asc
  tasks:
    - name: Adding the Jenkins repo signing key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: "{{ keyring }}"

    - name: Adding the Jenkins repo
      copy:
        content: "deb [signed-by={{ keyring }}] https://pkg.jenkins.io/debian-stable binary/"
        dest: /etc/apt/sources.list.d/jenkins.list

    - name: Updating CA certificates
      apt:
        name: ca-certificates
        state: latest
        update_cache: yes

    - name: Installing JDK and Jenkins
      apt:
        name:
          - openjdk-11-jre
          - jenkins

    - name: Ensure the Jenkins service is started
      service:
        name: jenkins
        state: started