---
- name: Filling in the inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add build host
      add_host:
        hostname: "{{ vm_ip }}"
        groups: jenkins

- name: Upgrade the instance
  hosts: jenkins
  become: true
  gather_facts: false
  tasks:
    - name: Wait for the instance is reachable
      wait_for_connection:

    - name: Gather facts for first time
      setup:

    - name: Update all packages to the latest version
      apt:
        update_cache: true
        upgrade: full
    
    - name: Reboot the instance
      reboot:

    - name: Wait for the instance is reachable
      wait_for_connection:

- name: Installing Jenkins
  hosts: jenkins
  become: true
  vars:
    - keyring: /usr/share/keyrings/jenkins-keyring.asc
  tasks:
    - name: Adding the Jenkins repo signing key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: "{{ keyring }}"

    - name: Adding the Jenkins repo
      copy:
        content: "deb [signed-by={{ keyring }}] https://pkg.jenkins.io/debian-stable binary/"
        dest: /etc/apt/sources.list.d/jenkins.list

    - name: Installing JDK and Jenkins
      apt:
        name:
          - openjdk-11-jre
          - jenkins
        update_cache: true

    - name: Ensure the Jenkins service is started
      service:
        name: jenkins
        state: started

    - debug:
        msg: "Jenkins address: http://{{inventory_hostname}}:8080\nAdmin password: {{ lookup('file', '/var/lib/jenkins/secrets/initialAdminPassword') }}"